import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from 'next/font/google'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "CashTrackr",
  description: "Generated by create next app",
  openGraph: {
    title: "CashTrackr - Personal Finance App",
    description: "Create budgets, track expenses, and visualize your spending.",
    url: "https://cashtrackr-page.vercel.app",
    siteName: "CashTrackr",
    images: [
      {
        url: "https://cashtrackr-page.vercel.app/preview.png",
        width: 1200,
        height: 630,
        alt: "CashTrackr Preview Image",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "CashTrackr - Personal Finance App",
    description: "Create budgets, track expenses, and visualize your spending.",
    images: ["https://cashtrackr-page.vercel.app/preview.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outfit.className}>
        {children}
      </body>
    </html>
  );
}
